/**
 * activity/getActivityDetail.js — Handler: activity/getActivityDetail
 *
 * ═══════════════════════════════════════════════════════════════════
 * PHASE 1 — 8 HAR-verified activity types
 * ═══════════════════════════════════════════════════════════════════
 *
 * CALLER: ActivityPage.openDetail() — when user taps an activity in the list
 *   ts.processHandler({
 *       type: 'activity', action: 'getActivityDetail',
 *       userId: UserInfoSingleton.getInstance().userId,
 *       actId: activityId,
 *       cycleType: cycleType,
 *       version: '1.0'
 *   }, callback);
 *
 * RESPONSE FORMAT (HAR verified — all 13 captures):
 *   {
 *       type: "activity",
 *       action: "getActivityDetail",
 *       userId: "...",
 *       actId: "...",
 *       cycleType: N,
 *       version: "1.0",
 *       act: { ... activity config (28 common fields + type-specific fields) },
 *       uact: { ... user activity state (progress, purchased, etc.) },
 *       forceEndTime: 0
 *   }
 *
 * ACT ID FORMAT: act_{actType}_{cycleType}
 *   Generated by getActivityBrief. This handler parses actId to determine type.
 *
 * DATA SOURCE: 100% EMBEDDED (no config JSON files for activities)
 *   All reward tables, prices, targets, etc. are HAR-verified constants.
 *
 * UACT PERSISTENCE: Stored in user DB under _activityState[actId]
 *   Fresh state initialized on first request. Updated on each request.
 *
 * STRICT RULES: NO STUB, OVERRIDE, FORCE, BYPASS, DUMMY, ASUMSI
 * NO rewardHandlers — this is a READ-ONLY detail handler.
 * Reward claiming handlers (buyNewServerGift, heroGiftReward, etc.)
 * are separate handlers for future phases.
 *
 * HAR REFERENCE: har-main-server-decoded.md
 *   [16/245] type 2007 RECHARGE_DAILY    — line 14926
 *   [17/245] type 2004 RECHARGE_GIFT    — line 16121
 *   [26/245] type 2003 NEW_SERVER_GIFT  — line 17409
 *   [19/245] type 5003 TODAY_DISCOUNT   — line 16517
 *   [30/245] type 5037 HERO_SUPER_GIFT  — line 17838
 *   [37/245] type 2001 HERO_GIFT        — line 20824
 *   [195/245] type 2002 HERO_ORANGE     — line 53138
 *   [38/245] type 1003 RECHARGE_3       — line 21023
 */

'use strict';

var MS_PER_DAY = 24 * 60 * 60 * 1000;
var { v4: uuidv4 } = require('uuid');

// ═══════════════════════════════════════════════════════════════
// ACTIVITY TYPE CONSTANTS
// ═══════════════════════════════════════════════════════════════

var ACTIVITY_TYPE = {
    LOGIN:                  1001,
    GROW:                   1002,
    RECHARGE_3:             1003,
    HERO_GIFT:              2001,
    HERO_ORANGE:            2002,
    NEW_SERVER_GIFT:        2003,
    RECHARGE_GIFT:          2004,
    RECHARGE_DAILY:         2007,
    TODAY_DISCOUNT:         5003,
    HERO_SUPER_GIFT:        5037
};

// ═══════════════════════════════════════════════════════════════
// ACTIVITY DETAIL CONFIG — HAR-verified, embedded constants
// ═══════════════════════════════════════════════════════════════
//
// Each entry contains the FULL act config from HAR.
// Structure: { common fields } + { type-specific fields }
// This is static data that the server returns for the detail view.
// The uact (user activity state) is separate — tracked per-user.

function emptyReward() {
    return {
        _normalReward: { _items: [] },
        _randReward: [],
        _anyReward: { _icon: '', _anyReward: [] }
    };
}

function makeReward(items) {
    return {
        _normalReward: { _items: items },
        _randReward: [],
        _anyReward: { _icon: '', _anyReward: [] }
    };
}

// ───────────────────────────────────────────────────────────
// TYPE 2007 — RECHARGE_DAILY (Daily accumulated top-up)
// HAR: [16/245] line 14926
// Structure: _days → { dayNum } → _items → { tier } → { _target, _reward }
// ───────────────────────────────────────────────────────────

var RECHARGE_DAILY_TIERS = {
    '1': { _des: 'Total top-up $0.99', __des: 'lang_2007_509', _target: 0.99,
        _reward: makeReward([{ _id: 2851, _num: 5 }, { _id: 122, _num: 1 }]) },
    '2': { _des: 'Total top-up $5', __des: 'lang_2007_509', _target: 5,
        _reward: makeReward([{ _id: 132, _num: 5000 }, { _id: 131, _num: 50000 }, { _id: 102, _num: 100000 }]) },
    '3': { _des: 'Total top-up $15', __des: 'lang_2007_509', _target: 15,
        _reward: makeReward([{ _id: 123, _num: 2 }, { _id: 122, _num: 5 }, { _id: 102, _num: 200000 }]) },
    '4': { _des: 'Total top-up $30', __des: 'lang_2007_509', _target: 30,
        _reward: makeReward([{ _id: 2851, _num: 50 }, { _id: 123, _num: 2 }]) },
    '5': { _des: 'Total top-up $60', __des: 'lang_2007_509', _target: 60,
        _reward: makeReward([{ _id: 2861, _num: 10 }, { _id: 2851, _num: 10 }]) },
    '6': { _des: 'Total top-up $100', __des: 'lang_2007_509', _target: 100,
        _reward: makeReward([{ _id: 2861, _num: 20 }, { _id: 2851, _num: 20 }]) }
};

function buildRechargeDailyDays() {
    var days = {};
    for (var d = 1; d <= 7; d++) {
        days[String(d)] = { _items: JSON.parse(JSON.stringify(RECHARGE_DAILY_TIERS)) };
    }
    return days;
}

// ───────────────────────────────────────────────────────────
// TYPE 2004 — RECHARGE_GIFT (Cumulative Top-up Gift)
// HAR: [17/245] line 16121
// Structure: _items → { tier } → { _target, _reward }
//           + _rankFirst, _rankSecondThird, _showItems[], _disableRank
// ───────────────────────────────────────────────────────────

var RECHARGE_GIFT_ITEMS = {
    '1':  { _des: '', __des: '', _target: 0.9,
        _reward: makeReward([{ _id: 131, _num: 20000 }, { _id: 132, _num: 800 }]) },
    '2':  { _des: '', __des: '', _target: 5,
        _reward: makeReward([{ _id: 101, _num: 100 }, { _id: 132, _num: 2500 }]) },
    '3':  { _des: '', __des: '', _target: 10,
        _reward: makeReward([{ _id: 101, _num: 200 }, { _id: 132, _num: 5000 }]) },
    '4':  { _des: '', __des: '', _target: 20,
        _reward: makeReward([{ _id: 123, _num: 3 }]) },
    '5':  { _des: ' <font color=0x000000>Activate Super Ultimate</font> <font color=0xff0000>High Strike</font><font color=0x000001></font>',
        __des: 'lang_2004_168', _target: 40,
        _reward: makeReward([{ _id: 1405, _num: 1 }]) },
    '6':  { _des: ' <font color=0x000000>Activate Super Ultimate</font> <font color=0xff0000>Planet Destroyer</font><font color=0x000000></font>',
        __des: 'lang_2004_167', _target: 60,
        _reward: makeReward([{ _id: 1404, _num: 1 }]) },
    '7':  { _des: '', __des: '', _target: 90,
        _reward: makeReward([{ _id: 123, _num: 10 }]) },
    '8':  { _des: '', __des: '', _target: 150,
        _reward: makeReward([{ _id: 4401, _num: 1 }]) },
    '9':  { _des: '', __des: '', _target: 250,
        _reward: makeReward([{ _id: 1508, _num: 1 }]) },
    '10': { _des: '', __des: '', _target: 600,
        _reward: makeReward([{ _id: 612, _num: 1 }]) },
    '11': { _des: '', __des: '', _target: 1000,
        _reward: makeReward([{ _id: 1600, _num: 1 }, { _id: 4401, _num: 1 }]) }
};

// ───────────────────────────────────────────────────────────
// TYPE 2003 — NEW_SERVER_GIFT (New Server Discount Pack)
// HAR: [26/245] line 17409
// Structure: _items → { packId } → { _limit, _price, _reward, _goodName, __goodName }
// ───────────────────────────────────────────────────────────

var NEW_SERVER_GIFT_ITEMS = {
    '1': { _limit: 7, _price: 4.99, _reward: makeReward([{ _id: 101, _num: 300 }, { _id: 101, _num: 300 }, { _id: 132, _num: 5000 }]),
        _goodName: '30 New Server Breakthrough Discount Pack', __goodName: 'lang_2003_500' },
    '2': { _limit: 5, _price: 4.99, _reward: makeReward([{ _id: 101, _num: 300 }, { _id: 101, _num: 300 }, { _id: 501, _num: 6 }]),
        _goodName: '30 New Server Awaken Discount Pack', __goodName: 'lang_2003_501' },
    '3': { _limit: 5, _price: 14.99, _reward: makeReward([{ _id: 101, _num: 980 }, { _id: 101, _num: 980 }, { _id: 123, _num: 5 }]),
        _goodName: '98 New Server Advanced SummonOrb Discount Pack3', __goodName: 'lang_2003_507' },
    '4': { _limit: 8, _price: 14.99, _reward: makeReward([{ _id: 101, _num: 980 }, { _id: 101, _num: 980 }, { _id: 132, _num: 10000 }]),
        _goodName: '98 New Server Breakthrough Discount Pack1', __goodName: 'lang_2003_505' },
    '5': { _limit: 5, _price: 14.99, _reward: makeReward([{ _id: 101, _num: 980 }, { _id: 101, _num: 980 }, { _id: 501, _num: 18 }]),
        _goodName: '98 New Server Awaken Discount Pack2', __goodName: 'lang_2003_506' },
    '6': { _limit: 5, _price: 59.99, _reward: makeReward([{ _id: 101, _num: 3880 }, { _id: 101, _num: 3880 }, { _id: 123, _num: 22 }]),
        _goodName: '388 New Server SummonOrb Discount Pack', __goodName: 'lang_2003_502' },
    '7': { _limit: 8, _price: 59.99, _reward: makeReward([{ _id: 101, _num: 3880 }, { _id: 101, _num: 3880 }, { _id: 501, _num: 68 }]),
        _goodName: '388 New Server Awaken Discount Pack', __goodName: 'lang_2003_503' },
    '8': { _limit: 4, _price: 89.99, _reward: makeReward([{ _id: 101, _num: 5880 }, { _id: 101, _num: 5880 }, { _id: 132, _num: 60000 }]),
        _goodName: '588 New Server Breakthrough Discount Pack', __goodName: 'lang_2003_504' }
};

// ───────────────────────────────────────────────────────────
// TYPE 5003 — TODAY_DISCOUNT (Discount Today)
// HAR: [19/245] line 16517
// Structure: _items → { slot } → { _randItems, _randGroup }
// _randItems: keyed item pool with buyType, cost, reward, weight
// _randGroup: weighted random selection config
// ───────────────────────────────────────────────────────────

var TODAY_DISCOUNT_ITEMS = {
    '0': {
        _randItems: {
            '1': { _id: 1, _buyType: 2,
                _cost: { _items: { '101': { _id: 101, _num: 1 } } },
                _reward: makeReward([{ _id: 102, _num: 50000 }]),
                _price: 0, _discount: '90% Off', __discount: 'lang_5003_620',
                _weight: 25, _goodName: 'Coin', __goodName: 'lang_5003_624' },
            '2': { _id: 2, _buyType: 2,
                _cost: { _items: { '101': { _id: 101, _num: 3 } } },
                _reward: makeReward([{ _id: 122, _num: 2 }]),
                _price: 0, _discount: '90% Off', __discount: 'lang_5003_620',
                _weight: 25, _goodName: 'Normal Summon Orb', __goodName: 'lang_5003_622' },
            '3': { _id: 3, _buyType: 2,
                _cost: { _items: { '101': { _id: 101, _num: 5 } } },
                _reward: makeReward([{ _id: 146, _num: 1 }]),
                _price: 0, _discount: '90% Off', __discount: 'lang_5003_620',
                _weight: 25, _goodName: 'Senzu Bean', __goodName: 'lang_5003_621' },
            '4': { _id: 4, _buyType: 2,
                _cost: { _items: { '101': { _id: 101, _num: 9 } } },
                _reward: makeReward([{ _id: 111, _num: 30 }]),
                _price: 0, _discount: '90% Off', __discount: 'lang_5003_620',
                _weight: 25, _goodName: 'Soul Stone', __goodName: 'lang_5003_623' }
        },
        _randGroup: { _groups: { '1': { _groupId: 1, _totalWeight: 100,
            _items: [
                { _itemId: 1, _num: 1, _weight: 25 },
                { _itemId: 2, _num: 1, _weight: 25 },
                { _itemId: 3, _num: 1, _weight: 25 },
                { _itemId: 4, _num: 1, _weight: 25 }
            ]
        }}}
    },
    '1': {
        _randItems: {
            '1': { _id: 1, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 132, _num: 4000 }, { _id: 102, _num: 180000 }]),
                _price: 0.99, _discount: '50% Off', __discount: 'lang_5003_598',
                _weight: 50, _goodName: 'Breakthrough Capsule', __goodName: 'lang_5003_580' },
            '2': { _id: 2, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 101, _num: 180 }, { _id: 102, _num: 60000 }]),
                _price: 0.99, _discount: '70% Off', __discount: 'lang_5012_430',
                _weight: 50, _goodName: '180 Gem', __goodName: 'lang_5003_565' }
        },
        _randGroup: { _groups: { '1': { _groupId: 1, _totalWeight: 100,
            _items: [
                { _itemId: 1, _num: 1, _weight: 50 },
                { _itemId: 2, _num: 1, _weight: 50 }
            ]
        }}}
    },
    '2': {
        _randItems: {
            '1': { _id: 1, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 132, _num: 6000 }, { _id: 102, _num: 380000 }]),
                _price: 1.99, _discount: '60% Off', __discount: 'lang_5012_431',
                _weight: 50, _goodName: 'Breakthrough Capsule', __goodName: 'lang_5003_580' },
            '2': { _id: 2, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 101, _num: 360 }, { _id: 102, _num: 120000 }]),
                _price: 1.99, _discount: '70% Off', __discount: 'lang_5012_430',
                _weight: 50, _goodName: '360 Gem', __goodName: 'lang_5003_597' }
        },
        _randGroup: { _groups: { '1': { _groupId: 1, _totalWeight: 100,
            _items: [
                { _itemId: 1, _num: 1, _weight: 50 },
                { _itemId: 2, _num: 1, _weight: 50 }
            ]
        }}}
    },
    '3': {
        _randItems: {
            '1': { _id: 1, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 123, _num: 3 }, { _id: 122, _num: 5 }]),
                _price: 2.99, _discount: '80% Off', __discount: 'lang_5012_429',
                _weight: 33, _goodName: 'Advanced Summon Orb', __goodName: 'lang_5003_603' },
            '2': { _id: 2, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 139, _num: 500 }, { _id: 135, _num: 1200 }]),
                _price: 2.99, _discount: '70% Off', __discount: 'lang_5012_430',
                _weight: 33, _goodName: 'Jade of Potara', __goodName: 'lang_5003_577' },
            '3': { _id: 3, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 136, _num: 5000 }, { _id: 102, _num: 100000 }]),
                _price: 2.99, _discount: '70% Off', __discount: 'lang_5012_430',
                _weight: 34, _goodName: 'Energy Stone', __goodName: 'lang_5003_601' }
        },
        _randGroup: { _groups: { '1': { _groupId: 1, _totalWeight: 100,
            _items: [
                { _itemId: 1, _num: 1, _weight: 33 },
                { _itemId: 2, _num: 1, _weight: 33 },
                { _itemId: 3, _num: 1, _weight: 34 }
            ]
        }}}
    },
    '4': {
        _randItems: {
            '1': { _id: 1, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 123, _num: 5 }, { _id: 122, _num: 8 }]),
                _price: 4.99, _discount: '80% Off', __discount: 'lang_5012_429',
                _weight: 50, _goodName: 'Advanced Summon Orb', __goodName: 'lang_5003_603' },
            '2': { _id: 2, _buyType: 1,
                _cost: { _items: {} },
                _reward: makeReward([{ _id: 139, _num: 800 }, { _id: 135, _num: 2000 }]),
                _price: 4.99, _discount: '70% Off', __discount: 'lang_5012_430',
                _weight: 50, _goodName: 'Jade of Potara', __goodName: 'lang_5003_577' }
        },
        _randGroup: { _groups: { '1': { _groupId: 1, _totalWeight: 100,
            _items: [
                { _itemId: 1, _num: 1, _weight: 50 },
                { _itemId: 2, _num: 1, _weight: 50 }
            ]
        }}}
    }
};

// ───────────────────────────────────────────────────────────
// TYPE 5037 — HERO_SUPER_GIFT (Hero Value Pack)
// HAR: [30/245] line 17838
// Structure: _showType, _items → { packId } → { _limit, _bg, _goodName, _price, _reward }
// ───────────────────────────────────────────────────────────

var HERO_SUPER_GIFT_ITEMS = {
    '1': { _limit: 1,
        _bg: '/activity/\u65b0\u670d\u6d3b\u52a8/xinfuyingxiongtehui_3.png?rnd=918311672116372',
        _goodName: 'Group SS Heroes 1 of 3 Pack', __goodName: 'lang_5037_1827',
        _price: 19.99, _reward: makeReward([{ _id: 496, _num: 1 }]) },
    '2': { _limit: 1,
        _bg: '/activity/\u65b0\u670d\u6d3b\u52a8/xinfuyingxiongtehui_4.png?rnd=587851672116377',
        _goodName: 'Bleeding SS Heroes 1 of 3 Pack', __goodName: 'lang_5037_1826',
        _price: 19.99, _reward: makeReward([{ _id: 498, _num: 1 }]) },
    '3': { _limit: 1,
        _bg: '/activity/\u65b0\u670d\u6d3b\u52a8/xinfuyingxiongtehui_5.png?rnd=471931672116379',
        _goodName: 'Single SS Heroes 1 of 3 Pack', __goodName: 'lang_5037_1828',
        _price: 19.99, _reward: makeReward([{ _id: 497, _num: 1 }]) }
};

// ───────────────────────────────────────────────────────────
// TYPE 2001 — HERO_GIFT (Hero Grand Kickback)
// HAR: [37/245] line 20824
// Structure: _items → { tier } → { _des, _target, _heroQualitys[], _reward._randReward[] }
// Note: _timeType=2, _startTime=0, _endTime=0 (no time limit)
// ───────────────────────────────────────────────────────────

var HERO_GIFT_ITEMS = {
    '1': {
        _des: 'Obtained an orange hero', __des: 'lang_2001_160',
        _target: 1,
        _heroQualitys: [5, 6, 7],
        _reward: {
            _normalReward: { _items: [] },
            _randReward: [{
                _icon: '/activity/\u65b0\u7528\u6237\u6d3b\u52a8/expcap.png',
                _randReward: { _groups: { '1': { _groupId: 1, _totalWeight: 100,
                    _items: [
                        { _itemId: 131, _num: 6800, _weight: 20 },
                        { _itemId: 131, _num: 8800, _weight: 50 },
                        { _itemId: 131, _num: 18800, _weight: 17 },
                        { _itemId: 131, _num: 28800, _weight: 10 },
                        { _itemId: 131, _num: 68800, _weight: 3 }
                    ]
                }}
            }}],
            _anyReward: { _icon: '', _anyReward: [] }
        }
    },
    '2': {
        _des: 'Obtained a purple hero', __des: 'lang_2001_161',
        _target: 1,
        _heroQualitys: [4],
        _reward: {
            _normalReward: { _items: [] },
            _randReward: [{
                _icon: '/activity/\u65b0\u7528\u6237\u6d3b\u52a8/gold.png',
                _randReward: { _groups: { '1': { _groupId: 1, _totalWeight: 100,
                    _items: [
                        { _itemId: 102, _num: 5800, _weight: 30 },
                        { _itemId: 102, _num: 6800, _weight: 35 },
                        { _itemId: 102, _num: 8800, _weight: 20 },
                        { _itemId: 102, _num: 18800, _weight: 12 },
                        { _itemId: 102, _num: 28800, _weight: 3 }
                    ]
                }}
            }}],
            _anyReward: { _icon: '', _anyReward: [] }
        }
    }
};

// ───────────────────────────────────────────────────────────
// TYPE 2002 — HERO_ORANGE (Orange Hero Assembly)
// HAR: [195/245] line 53138
// Structure: _items → { tier } → { _target, _heroQuality, _reward }
// Note: _timeType=2
// ───────────────────────────────────────────────────────────

var HERO_ORANGE_ITEMS = {
    '1':  { _target: 2,  _heroQuality: 5, _reward: makeReward([{ _id: 123, _num: 2 }]) },
    '2':  { _target: 5,  _heroQuality: 5, _reward: makeReward([{ _id: 123, _num: 2 }]) },
    '3':  { _target: 8,  _heroQuality: 5, _reward: makeReward([{ _id: 123, _num: 3 }]) },
    '4':  { _target: 1,  _heroQuality: 6, _reward: makeReward([{ _id: 123, _num: 2 }]) },
    '5':  { _target: 2,  _heroQuality: 6, _reward: makeReward([{ _id: 123, _num: 3 }]) },
    '6':  { _target: 3,  _heroQuality: 6, _reward: makeReward([{ _id: 123, _num: 4 }]) },
    '7':  { _target: 4,  _heroQuality: 6, _reward: makeReward([{ _id: 123, _num: 6 }]) },
    '8':  { _target: 6,  _heroQuality: 6, _reward: makeReward([{ _id: 123, _num: 10 }]) },
    '9':  { _target: 12, _heroQuality: 5, _reward: makeReward([{ _id: 123, _num: 3 }]) },
    '10': { _target: 18, _heroQuality: 5, _reward: makeReward([{ _id: 123, _num: 5 }]) },
    '11': { _target: 25, _heroQuality: 5, _reward: makeReward([{ _id: 123, _num: 5 }]) },
    '12': { _target: 35, _heroQuality: 5, _reward: makeReward([{ _id: 123, _num: 8 }]) }
};

// ───────────────────────────────────────────────────────────
// TYPE 1003 — RECHARGE_3 (7-Day Top-up At Will)
// HAR: [38/245] line 21023
// Structure: _items → { day } → { _des, _reward }
//           + _finalItem, _maxResignTimes, _resignCost{}, _advanceEndReward
// ───────────────────────────────────────────────────────────

var RECHARGE_3_DAY_REWARDS = {
    '1': { _des: 'Daily recharge for day 1 gift', __des: 'lang_1003_440',
        _reward: makeReward([{ _id: 101, _num: 88 }, { _id: 122, _num: 5 }]) },
    '2': { _des: 'Daily recharge for day 2 gift', __des: 'lang_1003_441',
        _reward: makeReward([{ _id: 101, _num: 88 }, { _id: 123, _num: 1 }]) },
    '3': { _des: 'Daily recharge for day 3 gift', __des: 'lang_1003_442',
        _reward: makeReward([{ _id: 101, _num: 88 }, { _id: 122, _num: 5 }]) },
    '4': { _des: 'Daily recharge for day 4 gift', __des: 'lang_1003_443',
        _reward: makeReward([{ _id: 101, _num: 88 }, { _id: 123, _num: 1 }]) },
    '5': { _des: 'Daily recharge for day 5 gift', __des: 'lang_1003_444',
        _reward: makeReward([{ _id: 101, _num: 88 }, { _id: 122, _num: 5 }]) },
    '6': { _des: 'Daily recharge for day 6 gift', __des: 'lang_1003_445',
        _reward: makeReward([{ _id: 101, _num: 88 }, { _id: 123, _num: 1 }]) },
    '7': { _des: 'Daily recharge for day 7 gift', __des: 'lang_1003_446',
        _reward: makeReward([{ _id: 101, _num: 88 }, { _id: 122, _num: 5 }]) }
};

var RECHARGE_3_FINAL_ITEM = {
    _des: 'Continuous recharge for 7 days gift', __des: 'lang_1003_452',
    _reward: makeReward([{ _id: 123, _num: 10 }])
};

// ═══════════════════════════════════════════════════════════════
// ACTIVITY METADATA — Common fields per type (HAR verified)
// ═══════════════════════════════════════════════════════════════
//
// These are the 28+ common fields that appear in every act object.
// Type-specific differences are noted per entry.

var ACTIVITY_META = {
    // ─── cycleType=2 (SERVER_OPEN) types ───

    2007: { // RECHARGE_DAILY
        _templateName: '（新版开服）每日累充',
        _name: 'Daily accumulated top-up',
        __name: 'lang_2007_678',
        _des: 'You can get generous rewards if you reach a certain ammount in daily accumulated top-up during the activity!',
        __des: 'lang_2007_679',
        _icon: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew35.png?rnd=649231590140442',
        _image: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew29.jpg?rnd=15451590140452',
        _displayIndex: 6,
        _cycleType: 2,
        _timeType: 1,
        _durationDay: 7,
        _displayExtend: 0
    },
    2004: { // RECHARGE_GIFT
        _templateName: '（开服）累充豪礼（新）',
        _name: 'Cumulative Top-up Gift',
        __name: 'lang_2004_170',
        _des: '  During the event time, make required amount of top-up to claim ultimate rewards!',
        __des: 'lang_2004_166',
        _icon: '/activity/\u5f3a\u8005\u4e4b\u8def/huodongnew107.png',
        _image: '/activity/\u6bcf\u5468\u7d2f\u5145/topUp1.jpg?rnd=310081649211036',
        _displayIndex: 4,
        _cycleType: 2,
        _timeType: 1,
        _durationDay: 7,
        _displayExtend: 1
    },
    2003: { // NEW_SERVER_GIFT
        _templateName: '（开服）新服特惠包（新）',
        _name: 'New Server Discount Pack',
        __name: 'lang_2003_165',
        _des: '',
        __des: '',
        _icon: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew42.png',
        _image: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew41.jpg',
        _displayIndex: 2,
        _cycleType: 2,
        _timeType: 1,
        _durationDay: 7,
        _displayExtend: 0
    },
    5003: { // TODAY_DISCOUNT
        _templateName: '（开服）今日特价（新）',
        _name: 'Discount Today',
        __name: 'lang_5003_342',
        _des: '',
        __des: '',
        _icon: '/activity/\u5f3a\u8005\u4e4b\u8def/huodongnew205.png?rnd=574051578983873',
        _image: '/activity/\u5f3a\u8005\u4e4b\u8def/huodong201new.jpg?rnd=565591583918819',
        _displayIndex: 3,
        _cycleType: 2,
        _timeType: 1,
        _durationDay: 7,
        _displayExtend: 0
    },
    5037: { // HERO_SUPER_GIFT — has different _oldUserVip and _oldUserOfflineDay
        _templateName: '新服特惠三选一礼包',
        _name: 'Hero Value Pack',
        __name: 'lang_5037_1604',
        _des: '',
        __des: '',
        _icon: '/activity/\u65b0\u670d\u6d3b\u52a8/xinfuyingxiongtehui_rukou.png?rnd=851641672116391',
        _image: '/activity/\u65b0\u670d\u6d3b\u52a8/yingxiongtehui_1.jpg?rnd=134041672116403',
        _displayIndex: 0,
        _cycleType: 2,
        _timeType: 1,
        _durationDay: 7,
        _oldUserVip: 9,       // Different from default 0
        _oldUserOfflineDay: 7, // Different from default 0
        _displayExtend: 1
    },

    // ─── cycleType=1 (NEW_USER) types ───

    2001: { // HERO_GIFT — _timeType=2, no start/end time
        _templateName: '（新版开服）英雄大返利',
        _name: 'Hero Grand Kickback',
        __name: 'lang_2001_162',
        _des: ' During the event time, get the chance to make the lucky draw every time you get  1 orange or purple quality hero! (Heroes you get from Altar shop exchange and Shards Compose are not included)',
        __des: 'lang_2001_159',
        _icon: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew39.png',
        _image: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew44.jpg',
        _displayIndex: 8,
        _cycleType: 1,
        _timeType: 2,          // Different from default 1
        _durationDay: 7,
        _noTimeLimit: true,     // _startTime=0, _endTime=0
        _displayExtend: 0
    },
    2002: { // HERO_ORANGE — _timeType=2, different timestamps
        _templateName: '(新版开服)橙将集结号',
        _name: 'Orange Hero Assembly',
        __name: 'lang_2002_164',
        _des: '  During the event time, the more orange quality heroes you unlock, the more rewards you\'ll get! (Heroes you get from Altar shop exchange and Shards Compose are not included)',
        __des: 'lang_2002_163',
        _icon: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew40.png?rnd=171461604461607',
        _image: '/activity/\u65b0\u670d\u6d3b\u52a8/huodongnew4.jpg?rnd=21921604461608',
        _displayIndex: 9,
        _cycleType: 1,
        _timeType: 2,          // Different from default 1
        _durationDay: 7,
        _displayExtend: 0
    },
    1003: { // RECHARGE_3
        _templateName: '（开服）7日任意充',
        _name: '7-Day Top-up At Will',
        __name: 'lang_1003_156',
        _des: '',
        __des: '',
        _icon: '/activity/\u65b0\u7528\u6237\u6d3b\u52a8/huodongnew372.png?rnd=558541576031269',
        _image: '/activity/\u65b0\u7528\u6237\u6d3b\u52a8/huodongnew389.jpg?rnd=759631576031273',
        _displayIndex: 85,
        _cycleType: 1,
        _timeType: 1,
        _durationDay: 7,
        _displayExtend: 0
    }
};

// ═══════════════════════════════════════════════════════════════
// COMMON ACT FIELD BUILDER
// ═══════════════════════════════════════════════════════════════

/**
 * Build the 28 common fields for any activity type.
 * @param {number} actType - Activity type ID
 * @param {string} actId - Activity ID (from getActivityBrief)
 * @param {object} config - Server config (for serverOpenDate)
 * @returns {object} Common act fields object
 */
function buildCommonActFields(actType, actId, config) {
    var meta = ACTIVITY_META[actType];
    if (!meta) return null;

    var serverOpenDate = config.serverOpenDate || Date.now();
    // Align startTime to midnight UTC+8 (matching HAR: 1775199600000 = 2026-04-02T00:00:00+08:00)
    var startTime = Math.floor(serverOpenDate / MS_PER_DAY) * MS_PER_DAY;
    var endTime = startTime + (meta._durationDay * MS_PER_DAY) - 1;

    // Type 2001 has no time limit
    if (meta._noTimeLimit) {
        startTime = 0;
        endTime = 0;
    }

    // Type 2002 uses different time calculation (user-based, offset by 1 day)
    // HAR shows: _startTime: 1775286000000 (day 2 00:00 UTC+8), _endTime: +7 days
    // For now, use server-based calculation (will be refined when user time tracking is implemented)
    if (actType === 2002) {
        // HAR shows this activity uses user create time + offset, not server open date
        // For Phase 1, approximate with server open date + 1 day offset
        startTime = serverOpenDate + MS_PER_DAY;
        startTime = Math.floor(startTime / MS_PER_DAY) * MS_PER_DAY;
        endTime = startTime + (meta._durationDay * MS_PER_DAY) - 1;
    }

    return {
        _id: actId,
        _templateId: '',
        _templateName: meta._templateName,
        _name: meta._name,
        __name: meta.__name,
        _des: meta._des,
        __des: meta.__des,
        _icon: meta._icon,
        _image: meta._image,
        _displayIndex: meta._displayIndex,
        _showRed: true,
        _activityType: actType,
        _cycleType: meta._cycleType,
        _enable: true,
        _timeType: meta._timeType,
        _newUserUsing: true,
        _isloop: false,
        _loopInterval: 0,
        _startDay: 0,
        _durationDay: meta._durationDay,
        _oldUserVip: meta._oldUserVip || 0,
        _oldUserServerOpenDay: 0,
        _oldUserServerOpenDayEnd: 0,
        _oldUserOfflineDay: meta._oldUserOfflineDay || 0,
        _startTime: startTime,
        _endTime: endTime,
        _loopCount: 0,
        _loopTag: '',
        _timestamp: startTime + 1310, // Small offset from startTime (HAR: 1775199600000 → 1775199601310)
        _hideos: '',
        _limitReward: { _items: {} }
    };
}

// ═══════════════════════════════════════════════════════════════
// TYPE-SPECIFIC ACT FIELD BUILDERS
// ═══════════════════════════════════════════════════════════════

/**
 * Build type-specific act fields (the unique fields per activity type).
 * @param {number} actType
 * @returns {object|null} Type-specific fields, or null if type not supported
 */
function buildTypeSpecificActFields(actType) {
    switch (actType) {

        case ACTIVITY_TYPE.RECHARGE_DAILY: // 2007
            return {
                _days: buildRechargeDailyDays(),
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 0
            };

        case ACTIVITY_TYPE.RECHARGE_GIFT: // 2004
            return {
                _items: JSON.parse(JSON.stringify(RECHARGE_GIFT_ITEMS)),
                _rankFirst: { _des: '', __des: '', _target: 0, _reward: emptyReward() },
                _rankSecondThird: { _des: '', __des: '', _target: 0, _reward: emptyReward() },
                _showItems: [612],
                _disableRank: true,
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 1
            };

        case ACTIVITY_TYPE.NEW_SERVER_GIFT: // 2003
            return {
                _items: JSON.parse(JSON.stringify(NEW_SERVER_GIFT_ITEMS)),
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 0
            };

        case ACTIVITY_TYPE.TODAY_DISCOUNT: // 5003
            return {
                _items: JSON.parse(JSON.stringify(TODAY_DISCOUNT_ITEMS)),
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 0
            };

        case ACTIVITY_TYPE.HERO_SUPER_GIFT: // 5037
            return {
                _showType: 1,
                _items: JSON.parse(JSON.stringify(HERO_SUPER_GIFT_ITEMS)),
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 1
            };

        case ACTIVITY_TYPE.HERO_GIFT: // 2001
            return {
                _items: JSON.parse(JSON.stringify(HERO_GIFT_ITEMS)),
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 0
            };

        case ACTIVITY_TYPE.HERO_ORANGE: // 2002
            return {
                _items: JSON.parse(JSON.stringify(HERO_ORANGE_ITEMS)),
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 0
            };

        case ACTIVITY_TYPE.RECHARGE_3: // 1003
            return {
                _items: JSON.parse(JSON.stringify(RECHARGE_3_DAY_REWARDS)),
                _finalItem: JSON.parse(JSON.stringify(RECHARGE_3_FINAL_ITEM)),
                _maxResignTimes: 2,
                _resignCost: { '1': 300, '2': 500 },
                _advanceEndReward: {},
                __ruleDes: null,
                _displayAdvance: 0,
                _displayExtend: 0
            };

        default:
            return null;
    }
}

// ═══════════════════════════════════════════════════════════════
// UACT BUILDER — Fresh user activity state
// ═══════════════════════════════════════════════════════════════

/**
 * Build fresh uact (user activity state) for a given activity type.
 * This is the initial state when a user first opens the detail view.
 * For Phase 1, all progress is zeroed (new server, no activity done yet).
 *
 * @param {number} actType - Activity type ID
 * @param {string} actId - Activity ID
 * @param {object} commonAct - The common act fields (for _startTime, _endTime)
 * @returns {object} Fresh uact object
 */
function buildFreshUact(actType, actId, commonAct) {
    // Common uact fields (present in all types)
    var uact = {
        _activityType: actType,
        _startTime: commonAct._startTime,
        _endTime: commonAct._endTime,
        _activityId: actId,
        _loopTag: '',
        _haveClick: true,  // HAR shows _haveClick:true on every detail request
        _gotRewards: { _items: {} }
    };

    switch (actType) {

        case ACTIVITY_TYPE.RECHARGE_DAILY: // 2007
            uact._days = {};
            for (var d = 1; d <= 7; d++) {
                uact._days[String(d)] = { _curCount: 0, _haveGotReward: {} };
            }
            break;

        case ACTIVITY_TYPE.RECHARGE_GIFT: // 2004
            uact._curCount = 0;
            uact._haveGotReward = {};
            for (var t = 1; t <= 11; t++) {
                uact._haveGotReward[String(t)] = false;
            }
            uact._rechargeTime = 0;
            break;

        case ACTIVITY_TYPE.NEW_SERVER_GIFT: // 2003
            uact._buyTimes = {};
            for (var p = 1; p <= 8; p++) {
                uact._buyTimes[String(p)] = 0;
            }
            break;

        case ACTIVITY_TYPE.TODAY_DISCOUNT: // 5003
            uact._items = {};
            for (var s = 0; s <= 4; s++) {
                uact._items[String(s)] = { _goodId: 0, _haveBrought: false };
            }
            uact._batchId = uuidv4();
            uact._lastRefreshTime = Date.now();
            break;

        case ACTIVITY_TYPE.HERO_SUPER_GIFT: // 5037
            uact._buyTimes = {};
            break;

        case ACTIVITY_TYPE.HERO_GIFT: // 2001
            uact._items = {
                '1': { _leftTimes: 0, _curCount: 0 },
                '2': { _leftTimes: 5, _curCount: 0 }
            };
            break;

        case ACTIVITY_TYPE.HERO_ORANGE: // 2002
            uact._items = {};
            for (var h = 1; h <= 12; h++) {
                uact._items[String(h)] = { _curCount: 0, _haveGotReward: false };
            }
            break;

        case ACTIVITY_TYPE.RECHARGE_3: // 1003
            uact._items = {};
            for (var rd = 1; rd <= 7; rd++) {
                uact._items[String(rd)] = { _canGetReward: false, _haveGotReward: false };
            }
            uact._haveGotFinalReward = false;
            uact._resignCount = 0;
            break;
    }

    return uact;
}

// ═══════════════════════════════════════════════════════════════
// UACT PERSISTENCE — Load / Save user activity state
// ═══════════════════════════════════════════════════════════════

/**
 * Load user activity state from DB.
 * Stored under userData._activityState[actId].
 * @param {object} db - Database module
 * @param {string} userId - User ID
 * @param {string} actId - Activity ID
 * @returns {object|null} Saved uact, or null if not found
 */
function loadUact(db, userId, actId) {
    try {
        var userData = db.getUser(userId);
        if (!userData || !userData._activityState) return null;
        return userData._activityState[actId] || null;
    } catch (e) {
        return null;
    }
}

/**
 * Save user activity state to DB.
 * @param {object} db - Database module
 * @param {string} userId - User ID
 * @param {string} actId - Activity ID
 * @param {object} uact - User activity state to save
 */
function saveUact(db, userId, actId, uact) {
    try {
        var userData = db.getUser(userId);
        if (!userData) return false;
        if (!userData._activityState) {
            userData._activityState = {};
        }
        userData._activityState[actId] = uact;
        db.setUser(userId, userData);
        return true;
    } catch (e) {
        return false;
    }
}

// ═══════════════════════════════════════════════════════════════
// PARSE ACT ID — Extract actType from act_{actType}_{cycleType}
// ═══════════════════════════════════════════════════════════════

/**
 * Parse actId format: act_{actType}_{cycleType}
 * @param {string} actId - Activity ID from request
 * @returns {{ actType: number, cycleType: number }|null}
 */
function parseActId(actId) {
    if (!actId || typeof actId !== 'string') return null;
    var parts = actId.split('_');
    if (parts.length !== 3 || parts[0] !== 'act') return null;
    var actType = parseInt(parts[1], 10);
    var cycleType = parseInt(parts[2], 10);
    if (isNaN(actType) || isNaN(cycleType)) return null;
    return { actType: actType, cycleType: cycleType };
}

// ═══════════════════════════════════════════════════════════════
// SUPPORTED TYPES CHECK
// ═══════════════════════════════════════════════════════════════

var SUPPORTED_TYPES = {};
SUPPORTED_TYPES[ACTIVITY_TYPE.RECHARGE_DAILY] = true;     // 2007
SUPPORTED_TYPES[ACTIVITY_TYPE.RECHARGE_GIFT] = true;       // 2004
SUPPORTED_TYPES[ACTIVITY_TYPE.NEW_SERVER_GIFT] = true;     // 2003
SUPPORTED_TYPES[ACTIVITY_TYPE.TODAY_DISCOUNT] = true;      // 5003
SUPPORTED_TYPES[ACTIVITY_TYPE.HERO_SUPER_GIFT] = true;     // 5037
SUPPORTED_TYPES[ACTIVITY_TYPE.HERO_GIFT] = true;           // 2001
SUPPORTED_TYPES[ACTIVITY_TYPE.HERO_ORANGE] = true;         // 2002
SUPPORTED_TYPES[ACTIVITY_TYPE.RECHARGE_3] = true;           // 1003

// ═══════════════════════════════════════════════════════════════
// MAIN HANDLER
// ═══════════════════════════════════════════════════════════════

/**
 * Handler: activity/getActivityDetail
 *
 * Returns full activity detail view data + user activity state.
 * This is a READ-ONLY handler — no rewards are claimed here.
 *
 * @param {object} request - { type, action, userId, actId, cycleType, version }
 * @param {object} ctx - Handler context { db, config, logger, buildDataResponse, buildErrorResponse }
 * @returns {object} Response via buildDataResponse
 */
async function handleGetActivityDetail(request, ctx) {
    var userId = request.userId;
    var actId = request.actId;
    var cycleType = request.cycleType;

    // ─── STEP 1: Validate request ───
    ctx.logger.step(1, 3, 'Validate request', 'running');
    ctx.logger.details('request',
        ['userId', userId ? userId.substring(0, 20) + '...' : 'MISSING'],
        ['actId', actId || 'MISSING'],
        ['cycleType', String(cycleType || 'MISSING')]
    );

    if (!userId || !actId) {
        ctx.logger.step(1, 3, 'Validate request', 'fail', 'userId or actId MISSING');
        return ctx.buildErrorResponse(8);
    }
    ctx.logger.step(1, 3, 'Validate request', 'pass');

    // ─── STEP 2: Parse actId → determine actType ───
    ctx.logger.step(2, 3, 'Parse actId', 'running');
    var parsed = parseActId(actId);
    if (!parsed) {
        ctx.logger.step(2, 3, 'Parse actId', 'fail', 'Invalid actId format: ' + actId);
        return ctx.buildErrorResponse(4);
    }

    var actType = parsed.actType;
    ctx.logger.details('parsed',
        ['actType', String(actType)],
        ['cycleType', String(parsed.cycleType)]
    );

    if (!SUPPORTED_TYPES[actType]) {
        ctx.logger.step(2, 3, 'Parse actId', 'fail', 'Activity type ' + actType + ' not supported in Phase 1');
        ctx.logger.details('supported', ['types', Object.keys(SUPPORTED_TYPES).join(', ')]);
        return ctx.buildErrorResponse(4);
    }
    ctx.logger.step(2, 3, 'Parse actId', 'pass');

    // ─── STEP 3: Build act (activity config) ───
    ctx.logger.step(3, 3, 'Build act config', 'running');

    var commonAct = buildCommonActFields(actType, actId, ctx.config);
    if (!commonAct) {
        ctx.logger.step(3, 3, 'Build act config', 'fail', 'No metadata for type ' + actType);
        return ctx.buildErrorResponse(4);
    }

    var typeSpecific = buildTypeSpecificActFields(actType);
    if (!typeSpecific) {
        ctx.logger.step(3, 3, 'Build act config', 'fail', 'Cannot build type-specific fields for ' + actType);
        return ctx.buildErrorResponse(4);
    }

    // Merge common + type-specific fields
    var act = Object.assign({}, commonAct, typeSpecific);

    ctx.logger.step(3, 3, 'Build act config', 'pass');
    ctx.logger.details('act',
        ['activityType', String(actType)],
        ['name', act._name],
        ['startTime', new Date(act._startTime).toISOString()],
        ['endTime', new Date(act._endTime).toISOString()]
    );

    // ─── STEP 4: Build/Load uact (user activity state) ───
    ctx.logger.step(4, 3, 'Build uact', 'running');

    // Try to load existing uact from DB
    var uact = loadUact(ctx.db, userId, actId);

    if (uact) {
        // Existing user state found — update _haveClick
        uact._haveClick = true;
        ctx.logger.details('uact', ['source', 'loaded from DB']);
    } else {
        // Fresh state for new user/activity
        uact = buildFreshUact(actType, actId, commonAct);
        ctx.logger.details('uact', ['source', 'fresh (new)']);
    }

    // Save uact back to DB
    saveUact(ctx.db, userId, actId, uact);

    ctx.logger.step(4, 3, 'Build uact', 'pass');

    // ─── STEP 5: Build response ───
    var responseData = {
        type: request.type || 'activity',
        action: request.action || 'getActivityDetail',
        userId: userId,
        actId: actId,
        cycleType: cycleType || parsed.cycleType,
        version: request.version || '1.0',
        act: act,
        uact: uact,
        forceEndTime: 0
    };

    ctx.logger.details('response',
        ['actType', String(actType)],
        ['actFields', String(Object.keys(act).length)],
        ['uactFields', String(Object.keys(uact).length)]
    );

    return ctx.buildDataResponse(0, responseData);
}

module.exports = handleGetActivityDetail;
